# Generated by Django 3.2.12 on 2022-07-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_etudiant_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.niveau'),
        ),
    ]
